```{r}
library(tidyquant)
library(ggplot2)
library(reshape2)
library(scales)
library(zoo)
library(dplyr)
```

```{r}
ticker <- "BTC-USD"
initial_date <- as.Date("2010-01-01")
final_date <- as.Date("2022-01-01")

btc_data <- tq_get(ticker, from = initial_date, to = final_date)

btc_data <- as.data.frame(btc_data)

ggplot(btc_data, aes(x = date, y = adjusted)) +
  geom_line(color = "steelblue", size = 1) +
  labs(
    title = "Cotação Histórica", ticker,
    subtitle = "",
    x = "Data",
    y = "Preço de Fechamento (USD)"
  ) +
  theme_minimal()
```

```{r}
periodo <- 5

btc_data$Retorno <- c(NA, diff(btc_data$adjusted) / head(btc_data$adjusted, -1) * 100)

btc_data$Retorno_p <- c(rep(NA, periodo), diff(btc_data$adjusted, lag = periodo) / head(btc_data$adjusted, -periodo) * 100)

btc_data$Retorno_p <- rollapply(btc_data$Retorno_p, width = 10, FUN = mean, fill = NA, align = "right")

btc_data$Proporcao <- (btc_data$adjusted - btc_data$open)/(btc_data$high - btc_data$low)

btc_data$Desvio <- rollapply(btc_data$Retorno, width = 5, FUN = sd, fill = NA, align = "right")

btc_data$Alvo <- lead(btc_data$Desvio, n = periodo)

```

```{r}

ggplot(data = data.frame(btc_data$Alvo), aes(x = btc_data$Alvo)) +
  geom_histogram(binwidth = 0.5, fill = "blue", color = "black") +
  labs(title = "Distribuição de Volatilidade", x = "Valores", y = "Frequência")

```

```{r}
colunas_numericas <- names(btc_data)[sapply(btc_data, is.numeric)]

matriz_cor <- cor(btc_data[, colunas_numericas], use = "complete.obs")

correl <- matriz_cor[, "Alvo"]

correl <- correl[!names(correl) %in% c("open", "high", "low", "close", "adjusted", "Alvo")]

print(correl)
```

```{r}
colunas_para_remover <- c("open", "high", "low", "close", "adjusted")
matriz_cor_filtrada <- matriz_cor[!rownames(matriz_cor) %in% colunas_para_remover, 
                                 !colnames(matriz_cor) %in% colunas_para_remover]

# Transformando a matriz em um data.frame longo
df_cor <- melt(matriz_cor_filtrada)

# Renomeando colunas para facilitar
colnames(df_cor) <- c("Var1", "Var2", "Correlacao")

max_cor <- max(df_cor$Correlacao, na.rm = TRUE)
min_cor <- min(df_cor$Correlacao, na.rm = TRUE)

# Plot
ggplot(df_cor, aes(x = Var2, y = Var1, fill = Correlacao)) +
  geom_tile(color = "white") +  # borda entre os quadrados
  geom_text(aes(label = round(Correlacao, 2)), size = 3, color = "white") +
  scale_fill_gradient2(low = "red", mid = "brown", high = "blue", 
                       midpoint = 0, limit = c(min_cor, max_cor), 
                       name = "Correlação") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold")) +
  labs(title = "Heatmap de Correlações")
```

```{r}
btc_data[btc_data == Inf | btc_data == -Inf] <- NA
btc_model <- btc_data
btc_model <- na.omit(btc_model)

```

```{r}
begin_train <- as.Date("2015-01-01")
end_train <- as.Date("2020-12-31")

test_begin <- as.Date("2021-01-01")
end_test <- Sys.Date() -1

btc_test <- btc_model[btc_model$date >= as.Date(begin_train) & btc_model$date <= as.Date(end_train)]

```
